import { Sparkles } from "lucide-react";
import StatusStamp from "./StatusStamp";
import { EvidencePacketIcon } from "./DoodleIcons";

const DEMO = {
  reportId: "NF-102",
  category: "Road Damage / Pothole",
  severity: "High",
  confidence: 87,
  observedEvidence: "Crater ~0.8m wide, exposed rebar, standing water along school footpath edge.",
  publicRisk: "Two-wheelers swerving into oncoming lane near a school gate at peak hours.",
  suggestedResolver: "BBMP Ward 89 — Roads & Infrastructure cell.",
  missingDetails: "Exact lane direction and a daytime wide-shot for crew sizing.",
  nextAction: "Route to Roads cell as High priority; request barricade until patched.",
};

function Field({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div>
      <div className="font-mono text-[10px] font-bold uppercase tracking-widest" style={{ color: accent ?? "#243B73" }}>
        {label}
      </div>
      <p className="font-body text-[13px] leading-snug text-ink/85">{value}</p>
    </div>
  );
}

export default function EvidencePacketPreview({ className = "" }: { className?: string }) {
  const packet = DEMO;
  return (
    <div
      className={`relative rounded-2xl border-2 border-dashed border-ink/40 bg-cream p-5 shadow-[6px_6px_0_0_rgba(58,31,27,0.12)] sm:p-7 ${className}`}
    >
      {/* perforation dots top edge */}
      <div
        className="pointer-events-none absolute -top-[5px] left-6 right-6 h-2.5"
        aria-hidden="true"
        style={{ backgroundImage: "radial-gradient(circle, rgba(58,31,27,0.25) 40%, transparent 41%)", backgroundSize: "18px 10px", backgroundRepeat: "repeat-x" }}
      />

      {/* header row */}
      <div className="mb-4 flex items-start justify-between gap-3 border-b-2 border-dotted border-ink/25 pb-4">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 shrink-0">
            <EvidencePacketIcon className="h-full w-full" />
          </div>
          <div>
            <div className="font-mono text-[10px] font-bold uppercase tracking-widest text-ink/50">AI Evidence Packet</div>
            <div className="font-display text-xl font-extrabold leading-none text-indigoc">{packet.reportId}</div>
          </div>
        </div>
        <StatusStamp label="AI Reviewed" tone="indigo" />
      </div>

      {/* meta chips */}
      <div className="mb-4 flex flex-wrap gap-2">
        <Chip label="Category" value={packet.category} />
        <Chip label="Severity" value={packet.severity} tone="#D72638" />
        <Chip label="Confidence" value={`${packet.confidence}%`} tone="#2E7D32" />
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Observed Evidence" value={packet.observedEvidence} />
        <Field label="Public Risk" value={packet.publicRisk} accent="#D72638" />
        <Field label="Suggested Resolver" value={packet.suggestedResolver} accent="#00A6A6" />
        <Field label="Missing Details" value={packet.missingDetails} accent="#C2410C" />
      </div>

      {/* recommended next action — emphasized */}
      <div className="mt-4 rounded-xl border border-saffron/40 bg-saffron/10 p-3">
        <div className="font-mono text-[10px] font-bold uppercase tracking-widest text-saffron">Recommended Next Action</div>
        <p className="font-body text-[13px] font-semibold leading-snug text-ink">{packet.nextAction}</p>
      </div>

      <div className="mt-4 flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest text-ink/45">
        <Sparkles className="h-3 w-3 text-lotus" />
        Generated by Gemini
      </div>
    </div>
  );
}

function Chip({ label, value, tone = "#243B73" }: { label: string; value: string; tone?: string }) {
  return (
    <span className="inline-flex items-baseline gap-1.5 rounded-lg border bg-white/60 px-2.5 py-1" style={{ borderColor: `${tone}40` }}>
      <span className="font-mono text-[9px] font-bold uppercase tracking-wider text-ink/45">{label}</span>
      <span className="font-display text-xs font-extrabold" style={{ color: tone }}>{value}</span>
    </span>
  );
}
