/**
 * Lightweight i18n: static UI-string translation with English as the source.
 * Non-English strings are pre-generated by Gemini into translations.json
 * (see scripts/gen-i18n.mjs) so runtime lookups are instant and offline.
 * Dynamic AI content is translated live via /api/translate instead.
 */
import React, { createContext, useContext, useEffect, useState } from "react";
import en from "./en.json";
import generated from "./translations.json";

export type LangCode = "en" | "hi" | "kn" | "ta" | "te" | "bn" | "mr";

// Native-script labels so each option is legible to its own speakers.
export const LANGUAGES: { code: LangCode; label: string; english: string }[] = [
  { code: "en", label: "English", english: "English" },
  { code: "hi", label: "हिन्दी", english: "Hindi" },
  { code: "kn", label: "ಕನ್ನಡ", english: "Kannada" },
  { code: "ta", label: "தமிழ்", english: "Tamil" },
  { code: "te", label: "తెలుగు", english: "Telugu" },
  { code: "bn", label: "বাংলা", english: "Bengali" },
  { code: "mr", label: "मराठी", english: "Marathi" },
];

const DICTS: Record<string, Record<string, string>> = { en, ...(generated as Record<string, Record<string, string>>) };

type Ctx = { lang: LangCode; setLang: (l: LangCode) => void; t: (key: string) => string };
const LangContext = createContext<Ctx>({ lang: "en", setLang: () => {}, t: (k) => k });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const saved = typeof localStorage !== "undefined" ? localStorage.getItem("nammafix.lang") : null;
    return (saved as LangCode) || "en";
  });

  const setLang = (l: LangCode) => {
    setLangState(l);
    try { localStorage.setItem("nammafix.lang", l); } catch {}
  };

  // Keep <html lang> in sync (also covers the initial render).
  useEffect(() => { if (typeof document !== "undefined") document.documentElement.lang = lang; }, [lang]);

  // Fall back to English, then the raw key, so a missing translation never blanks the UI.
  const t = (key: string) => DICTS[lang]?.[key] ?? (en as Record<string, string>)[key] ?? key;

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export const useT = () => useContext(LangContext);
